version: '3'
services:
  node-app:
    build: 
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - .:/app:ro
    environment:
      - NODE_ENV=development
      - MONGO_DB_NAME=test
    command: npm run dev

  database:
    ports:
      - "27017:27017"

  load-balancer:
    ports:
      - "3000:80"